# Language and env

language: node_js
node_js: 'node'

# What is built

branches:
  only:
  - master

# Travis Lifecycle
install:
  - npm ci
  - npm run download

script:
  - npm run build

deploy:
  skip_cleanup: true
  provider: script
  script: bash ./tools/deploy.sh
  on:
    branch: master


# Other configs

git:
  depth: 5

cache:
  timeout: 86400
  directories:
  - data