language: node_js
node_js: 'node'

install:
  - npm ci
  - npm run download

cache:
  timeout: 86400
  directories:
  - data

script:
  - npm run build

deploy:
  skip_cleanup: true
  provider: script
  script: bash ./tools/deploy.sh
  on:
    branch: master
