language: node_js
node_js: 'node'

install:
  - npm i -g npm@5.7.1 # this should be deleted once 5.7.X is out of "pre-release"
  - npm ci
  - npm run download

cache:
  timeout: 86400
  directories:
  - data

script:
  - npm run build

deploy:
  skip_cleanup: true
  provider: script
  script: bash ./tools/deploy.sh
  on:
    branch: master

git:
  depth: 5